import { Component } from '@angular/core';
import {  JobCard } from '../job-card/job-card';
import { FormsModule } from '@angular/forms';
import type { Job } from '../../models/job.model';

@Component({
  selector: 'app-job-cards-container',
  imports: [JobCard, FormsModule],
  templateUrl: './job-cards-container.html',
  styleUrl: './job-cards-container.css',
})
export class JobCardsContainer {

  sortOptions = ['Best match', 'Most recent', 'Highest salary'];
  selectedSort = 'Best match';

   jobs: Job[] = [
  {
    id: 1,
    initials: 'NL',
    title: 'Senior Frontend Engineer',
    company: 'Nile Logic',
    location: 'New Cairo, Egypt',
    postedAgo: '2h ago',
    tags: ['Remote', 'Full-time', 'Senior'],
    salaryMin: 55,
    salaryMax: 75,
    matchScore: 92,
    description: 'Build the next generation of our analytics platform with React, TypeScript and a modern internal design system. You will own the component architecture end to end.',
  },
  {
    id: 2,
    initials: 'TC',
    title: 'Backend Engineer',
    company: 'TechCorp',
    location: 'Cairo, Egypt',
    postedAgo: '1d ago',
    tags: ['On-site', 'Full-time', 'Mid-level'],
    salaryMin: 30,
    salaryMax: 45,
    matchScore: 65,
    description: 'Join our backend team to build scalable APIs and microservices using Node.js and PostgreSQL.',
  },
  {
    id: 1,
    initials: 'NL',
    title: 'Senior Frontend Engineer',
    company: 'Nile Logic',
    location: 'New Cairo, Egypt',
    postedAgo: '2h ago',
    tags: ['Remote', 'Full-time', 'Senior'],
    salaryMin: 55,
    salaryMax: 75,
    matchScore: 92,
    description: 'Build the next generation of our analytics platform with React, TypeScript and a modern internal design system. You will own the component architecture end to end.',
  },
  {
    id: 2,
    initials: 'TC',
    title: 'Backend Engineer',
    company: 'TechCorp',
    location: 'Cairo, Egypt',
    postedAgo: '1d ago',
    tags: ['On-site', 'Full-time', 'Mid-level'],
    salaryMin: 30,
    salaryMax: 45,
    matchScore: 65,
    description: 'Join our backend team to build scalable APIs and microservices using Node.js and PostgreSQL.',
  },
  {
    id: 1,
    initials: 'NL',
    title: 'Senior Frontend Engineer',
    company: 'Nile Logic',
    location: 'New Cairo, Egypt',
    postedAgo: '2h ago',
    tags: ['Remote', 'Full-time', 'Senior'],
    salaryMin: 55,
    salaryMax: 75,
    matchScore: 92,
    description: 'Build the next generation of our analytics platform with React, TypeScript and a modern internal design system. You will own the component architecture end to end.',
  },
  {
    id: 2,
    initials: 'TC',
    title: 'Backend Engineer',
    company: 'TechCorp',
    location: 'Cairo, Egypt',
    postedAgo: '1d ago',
    tags: ['On-site', 'Full-time', 'Mid-level'],
    salaryMin: 30,
    salaryMax: 45,
    matchScore: 65,
    description: 'Join our backend team to build scalable APIs and microservices using Node.js and PostgreSQL.',
  },
  {
    id: 1,
    initials: 'NL',
    title: 'Senior Frontend Engineer',
    company: 'Nile Logic',
    location: 'New Cairo, Egypt',
    postedAgo: '2h ago',
    tags: ['Remote', 'Full-time', 'Senior'],
    salaryMin: 55,
    salaryMax: 75,
    matchScore: 92,
    description: 'Build the next generation of our analytics platform with React, TypeScript and a modern internal design system. You will own the component architecture end to end.',
  },
  {
    id: 2,
    initials: 'TC',
    title: 'Backend Engineer',
    company: 'TechCorp',
    location: 'Cairo, Egypt',
    postedAgo: '1d ago',
    tags: ['On-site', 'Full-time', 'Mid-level'],
    salaryMin: 30,
    salaryMax: 45,
    matchScore: 65,
    description: 'Join our backend team to build scalable APIs and microservices using Node.js and PostgreSQL.',
  },
  {
    id: 1,
    initials: 'NL',
    title: 'Senior Frontend Engineer',
    company: 'Nile Logic',
    location: 'New Cairo, Egypt',
    postedAgo: '2h ago',
    tags: ['Remote', 'Full-time', 'Senior'],
    salaryMin: 55,
    salaryMax: 75,
    matchScore: 92,
    description: 'Build the next generation of our analytics platform with React, TypeScript and a modern internal design system. You will own the component architecture end to end.',
  },
  {
    id: 2,
    initials: 'TC',
    title: 'Backend Engineer',
    company: 'TechCorp',
    location: 'Cairo, Egypt',
    postedAgo: '1d ago',
    tags: ['On-site', 'Full-time', 'Mid-level'],
    salaryMin: 30,
    salaryMax: 45,
    matchScore: 65,
    description: 'Join our backend team to build scalable APIs and microservices using Node.js and PostgreSQL.',
  },
  {
    id: 1,
    initials: 'NL',
    title: 'Senior Frontend Engineer',
    company: 'Nile Logic',
    location: 'New Cairo, Egypt',
    postedAgo: '2h ago',
    tags: ['Remote', 'Full-time', 'Senior'],
    salaryMin: 55,
    salaryMax: 75,
    matchScore: 92,
    description: 'Build the next generation of our analytics platform with React, TypeScript and a modern internal design system. You will own the component architecture end to end.',
  },
  {
    id: 2,
    initials: 'TC',
    title: 'Backend Engineer',
    company: 'TechCorp',
    location: 'Cairo, Egypt',
    postedAgo: '1d ago',
    tags: ['On-site', 'Full-time', 'Mid-level'],
    salaryMin: 30,
    salaryMax: 45,
    matchScore: 65,
    description: 'Join our backend team to build scalable APIs and microservices using Node.js and PostgreSQL.',
  },
  
];
}
